export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_REQUEST_SUCCESS = "FETCH_POST_REQUEST_SUCCESS";
export const FETCH_POST_REQUEST_FAIL = "FETCH_POST_REQUEST_FAIL";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_REQUEST_SUCCESS = "FETCH_USER_REQUEST_SUCCESS";
export const FETCH_USER_REQUEST_FAIL = "FETCH_USER_REQUEST_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
